export const defaultTheme = {
  colorBlack: "#333333",
  colorWhite: "#ffffff",
  colorGray: "#F6F6F6",
  colorBackgroundPageBuy: "#F7F7F7",
  colorBlue: "#D8ECFE",
  colorLightGreen: "#E1EDCE",
  colorGreen: "#88AA4D",
  colorLightRed: "#F8DDD7",
  colorRed: "#F75531",
  colorOrange: "#FC9B27",
  colorButtonHover: "#FC7427",
  maxWidth: "1280px",
  pagePadding: "90px",
  indent: "20px",
  fontFamily: '"Inter", "Arial", sans-serif',
  fonstSizeTitleH1: "44px",
  fonstSizeTitleH2: "36px",
  fonstSizeTitleH3: "32px",
  fonstSizeTitleH4: "24px",
  fontSizeDefault: "18px",
  pageWidth: "1280px"
};
